<script type="text/javascript" src={{ asset('vendor/datatables/js/jquery.dataTables.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/jquery.dataTables.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/dataTables.buttons.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/buttons.flash.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/buttons.html5.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/buttons.print.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/buttons.colVis.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/jszip.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/pdfmake.min.js') }}></script>
<script type="text/javascript" src={{ asset('vendor/datatables/js/vfs_fonts.js') }}></script>
